title: "Chess Openings"
description: "A website about various chess openings"
posts_dir: _posts

baseurl: "/ip-chess-openings"
url: ""

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      data: "site_info.yml"

theme: minima
markdown: kramdown
